### ISSUE TITLE
Would you like to have some more tests?

### ISSUE THREAD

**Issue by wxiaoguang** [lpilp/simplesm2#3]
Hi, thank you very much for this great project. I am using it and it works well.

I think we could add more tests to cover the behaviors, if you would agree, I could propose some PRs.

Thank you again.

**Comment by lpilp** [comment]
OK，没有问题

**Comment by wxiaoguang** [comment]
->  Add tests #4

**Comment by wxiaoguang** [comment]
->  Re-format code #5
